### ISSUE TITLE
module.exports rather than export default

### ISSUE THREAD

**Issue by reharik** [sindresorhus/titleize#5]
Hi, currently titleize/index.js' first line is
`export default function titleize(string) {`
This seems to break a utility script I have that is not babelized.  When I change it to 
`module.exports = function titleize(string) {`
the module works fine.
I noticed that "humanize-string" does module.exports and was hoping you could make this one do the same thing. 
Thanks,
Raif

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by ACPK** [comment]
@sindresorhus I hit this same issue when updating to Next.js 12. I have enabled Next's `swcMinify` function and thus removed Babel.

I skimmed the comments in the Gist above, but I don't see what to change. Currently, I am using `import titleize from "titleize";`
